### ISSUE TITLE
User can modify IdP display name to clash with another IdP and portal doesn't complain

### ISSUE THREAD

**Issue by alexstuart** [philsmart/metadata-management-api#11]
It's possible to give an existing IdP the `md:OrganizationDisplayName` of another IdP. This is not allowed by the checking toolset, and it needs to be communicated between the portal and API somehow.

**Comment by philsmart** [comment]
Hi Alex,

There is no check for this your right. I will look to add one. Slightly more involved than current checks, as no referential integrity checks are performed on EntityDescriptors (only with Members).

**Comment by alexstuart** [comment]
Looks like the check is in https://github.com/ukf/ukf-mda/blob/master/src/main/java/uk/org/ukfederation/mda/IdPDisplayNameDuplicateDetectingStage.java.

**Comment by philsmart** [comment]
great, thanks for update, should be able to include that in an MDA stage.

**Comment by philsmart** [comment]
Just getting to the crux of this, if I use the existing stage to provide this functionality (which is my preferred approach), on ADD or Update of a single EntityDescriptor, all EntityDescriptors will be checked. Consequently, an error could be generated from an Entity the user would not be expecting. It is however unlikely that this scenario will happen, as the integrity of the EntityDescriptors already stored should be sound. 

Just wanted to double check this was fine.

**Comment by rhyssmith** [comment]
That's fine, it shouldn't happen anyway, and this won't break anything.

**Comment by philsmart** [comment]
Check is now in version https://github.com/philsmart/metadata-management-api/tree/0.9.17
