### ISSUE TITLE
README.md does not indicate that API has a required HTTP header X_MDMAN_PRIORITY

### ISSUE THREAD

**Issue by alexstuart** [philsmart/metadata-management-api#12]
https://github.com/philsmart/metadata-management-api/blob/master/src/main/java/uk/ac/jisc/saml/mdman/controller/EntityMetadataManagementApi.java seems to indicate that X_MDMAN_PRIORITY is a required HTTP header (line 401) yet the API documentation in README.md does not mention this header. Is X_MDMAN_PRIORITY required? If it is, and README.md is the definitive API documentation, then README.md needs updating to include this (and any other) required HTTP header.

**Comment by philsmart** [comment]
README.md is not authoritative - it is kind of an half updated attempt and will be completed when version 1.0 happens. The up to date document is hosted at:

https://api.dev.ja.net/api.html

**Comment by philsmart** [comment]
Let me know if that helps.

**Comment by alexstuart** [comment]
Thanks! That's the information I was looking for. I guess this issue is then asking to ditch the bulk of README.md and replace it with a preamble and a link to the up-to-date documentation.

**Comment by philsmart** [comment]
Yes, will do that today. Will close once done.

**Comment by philsmart** [comment]
Simplified it for now. Will close this issue, but will at some point make the readme identical to the only HTML RAML document. Will open a new ticket for that.
